### ISSUE TITLE
Remove Matlab Wrapper

### ISSUE THREAD

**Issue by tknopp** [MagneticResonanceImaging/MRIRecoBenchmarks#1]
In https://github.com/MagneticResonanceImaging/MRIRecoBenchmarks/tree/master/benchmark1 we currently used Matlab to execute the BART commands. We should change that to https://github.com/JakobAsslaender/BartIO.jl. 

@aTrotier: Would you like to give this a go since you know BartIO better than me?

Next step would then be to create `benchmark2`, which would be dedicated to CS. There we will use https://github.com/aTrotier/MRIRecoVsBART_Benchmark

**Comment by aTrotier** [comment]
@JakobAsslaender Maybe we should do a release of BartIO. It will be easier to manage the package, especially in Pluto Notebook.

**Comment by aTrotier** [comment]
Do you want to create a benchmark2 based on the same model as benchmark1 ?

**Comment by tknopp** [comment]
Not yet, I want to cleanup benchmark1 a little bit before we move on. But yes afterwards we should create benchmark2.

**Comment by tknopp** [comment]
This is done now.

**Comment by JakobAsslaender** [comment]
Are you suggesting to add BartIO to the Julia registry? I can do so if y'all think this package is valuable enough...

**Comment by tknopp** [comment]
Yes I think so. The benefit is that this gives us versioning and MRIRecoBenchmarks can rely on it. One question is, if you want to move it to the `https://github.com/MagneticResonanceImaging` umbrella. The other question other question is, if the name `Bart.jl` or `BART.jl` is more suitable. If I get it right, its main purpose now is to call out to BART and not just to load the data.

**Comment by JakobAsslaender** [comment]
Ok, will do soon!

**Comment by aTrotier** [comment]
Yes, I have to use the writing functions only for a few applications like
subspace reconstruction.

Le lun. 19 sept. 2022 à 18:49, Jakob Assländer ***@***.***> a
écrit :
